# Chronic Kidney Disease Data Analysis

In [226]:
import pandas as pd

In [227]:
import numpy as np

In [228]:
import matplotlib.pyplot as plt

In [229]:
pd.set_option('display.max_rows', None)

## Load data from csv file

In [230]:
df = pd.read_csv('chronic_kidney_disease.csv')

In [231]:
df.describe()

age          bp          sg          al          su         bgr  \
count  391.000000  388.000000  353.000000  354.000000  351.000000  356.000000   
mean    51.483376   76.469072    1.017408    1.016949    0.450142  148.036517   
std     17.169714   13.683637    0.005717    1.352679    1.099191   79.281714   
min      2.000000   50.000000    1.005000    0.000000    0.000000   22.000000   
25%     42.000000   70.000000    1.010000    0.000000    0.000000   99.000000   
50%     55.000000   80.000000    1.020000    0.000000    0.000000  121.000000   
75%     64.500000   80.000000    1.020000    2.000000    0.000000  163.000000   
max     90.000000  180.000000    1.025000    5.000000    5.000000  490.000000   

               bu          sc         sod         pot        hemo  
count  381.000000  383.000000  313.000000  312.000000  348.000000  
mean    57.425722    3.072454  137.528754    4.627244   12.526437  
std     50.503006    5.741126   10.408752    3.193904    2.912587  
min      1.500000    0.400000    4.500000    2.500000    3.100000  
25%     27.000000    0.900000  135.000000    3.800000   10.300000  
50%     42.000000    1.300000  138.000000    4.400000   12.650000  
75%     66.000000    2.800000  142.000000    4.900000   15.000000  
max    391.000000   76.000000  163.000000   47.000000   17.800000

# column names

In [232]:
df.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'class'],
      dtype='object')

# remove null values of main features and convert to integer

In [233]:
df = df.loc[df['sg'].notnull()]

In [234]:
df = df.loc[df['rbcc'].notnull()]

In [235]:
df = df.loc[df['al'].notnull()]

In [236]:
df = df.loc[df['hemo'].notnull()]

In [237]:
df = df.loc[df['sc'].notnull()]

In [238]:
df = df.loc[df['pcv'].notnull()]

In [239]:
df['class']=df['class'].replace({'ckd\t':1, 'ckd':1, 'notckd':2})

In [240]:
df

age     bp     sg   al   su       rbc        pc         pcc          ba  \
0    48.0   80.0  1.020  1.0  0.0       NaN    normal  notpresent  notpresent   
3    48.0   70.0  1.005  4.0  0.0    normal  abnormal     present  notpresent   
4    51.0   80.0  1.010  2.0  0.0    normal    normal  notpresent  notpresent   
5    60.0   90.0  1.015  3.0  0.0       NaN       NaN  notpresent  notpresent   
7    24.0    NaN  1.015  2.0  4.0    normal  abnormal  notpresent  notpresent   
8    52.0  100.0  1.015  3.0  0.0    normal  abnormal     present  notpresent   
9    53.0   90.0  1.020  2.0  0.0  abnormal  abnormal     present  notpresent   
11   63.0   70.0  1.010  3.0  0.0  abnormal  abnormal     present  notpresent   
12   68.0   70.0  1.015  3.0  1.0       NaN    normal     present  notpresent   
14   68.0   80.0  1.010  3.0  2.0    normal  abnormal     present     present   
15   40.0   80.0  1.015  3.0  0.0       NaN    normal  notpresent  notpresent   
18   60.0  100.0  1.025  0.0  3.0       NaN    normal  notpresent  notpresent   
19   62.0   60.0  1.015  1.0  0.0       NaN  abnormal     present  notpresent   
20   61.0   80.0  1.015  2.0  0.0  abnormal  abnormal  notpresent  notpresent   
22   48.0   80.0  1.025  4.0  0.0    normal  abnormal  notpresent  notpresent   
24   42.0  100.0  1.015  4.0  0.0    normal  abnormal  notpresent     present   
25   61.0   60.0  1.025  0.0  0.0       NaN    normal  notpresent  notpresent   
26   75.0   80.0  1.015  0.0  0.0       NaN    normal  notpresent  notpresent   
27   69.0   70.0  1.010  3.0  4.0    normal  abnormal  notpresent  notpresent   
31   73.0   90.0  1.015  3.0  0.0       NaN  abnormal     present  notpresent   
32   61.0   90.0  1.010  1.0  1.0       NaN    normal  notpresent  notpresent   
35   65.0   90.0  1.020  2.0  1.0  abnormal    normal  notpresent  notpresent   
39   82.0   80.0  1.010  2.0  2.0    normal       NaN  notpresent  notpresent   
40   46.0   90.0  1.010  2.0  0.0    normal  abnormal  notpresent  notpresent   
42   47.0  100.0  1.010  0.0  0.0       NaN    normal  notpresent  notpresent   
43   35.0   80.0  1.010  1.0  0.0  abnormal       NaN  notpresent  notpresent   
46   48.0   70.0  1.015  0.0  0.0       NaN    normal  notpresent  notpresent   
48   73.0   70.0  1.005  0.0  0.0    normal    normal  notpresent  notpresent   
49   60.0   70.0  1.010  2.0  0.0    normal  abnormal     present  notpresent   
52   53.0   90.0  1.015  0.0  0.0       NaN    normal  notpresent  notpresent   
53   62.0   80.0  1.015  0.0  5.0       NaN       NaN  notpresent  notpresent   
54   63.0   80.0  1.010  2.0  2.0    normal       NaN  notpresent  notpresent   
56   76.0   70.0  1.015  3.0  4.0    normal  abnormal     present  notpresent   
58   73.0   80.0  1.020  2.0  0.0  abnormal  abnormal  notpresent  notpresent   
62   15.0   60.0  1.020  3.0  0.0       NaN    normal  notpresent  notpresent   
69   26.0   70.0  1.015  0.0  4.0       NaN    normal  notpresent  notpresent   
70   61.0   80.0  1.015  0.0  4.0       NaN    normal  notpresent  notpresent   
71   46.0   60.0  1.010  1.0  0.0    normal    normal  notpresent  notpresent   
74   56.0   90.0  1.015  2.0  0.0  abnormal  abnormal  notpresent  notpresent   
76   48.0   80.0  1.005  4.0  0.0  abnormal  abnormal  notpresent     present   
77   67.0   70.0  1.010  1.0  0.0       NaN    normal  notpresent  notpresent   
79   56.0   80.0  1.010  1.0  0.0       NaN    normal  notpresent  notpresent   
80   74.0   80.0  1.010  0.0  0.0       NaN    normal  notpresent  notpresent   
84   59.0   70.0  1.010  3.0  0.0    normal  abnormal  notpresent  notpresent   
87   70.0  100.0  1.005  1.0  0.0    normal  abnormal     present  notpresent   
90   63.0  100.0  1.010  2.0  2.0    normal    normal  notpresent     present   
91   56.0   70.0  1.015  4.0  1.0  abnormal    normal  notpresent  notpresent   
92   71.0   70.0  1.010  3.0  0.0    normal  abnormal     present     present   
93   73.0  100.0  1.010  3.0  2.0  ab

In [241]:
df['class']=df['class'].astype(int)

In [242]:
df

age     bp     sg   al   su       rbc        pc         pcc          ba  \
0    48.0   80.0  1.020  1.0  0.0       NaN    normal  notpresent  notpresent   
3    48.0   70.0  1.005  4.0  0.0    normal  abnormal     present  notpresent   
4    51.0   80.0  1.010  2.0  0.0    normal    normal  notpresent  notpresent   
5    60.0   90.0  1.015  3.0  0.0       NaN       NaN  notpresent  notpresent   
7    24.0    NaN  1.015  2.0  4.0    normal  abnormal  notpresent  notpresent   
8    52.0  100.0  1.015  3.0  0.0    normal  abnormal     present  notpresent   
9    53.0   90.0  1.020  2.0  0.0  abnormal  abnormal     present  notpresent   
11   63.0   70.0  1.010  3.0  0.0  abnormal  abnormal     present  notpresent   
12   68.0   70.0  1.015  3.0  1.0       NaN    normal     present  notpresent   
14   68.0   80.0  1.010  3.0  2.0    normal  abnormal     present     present   
15   40.0   80.0  1.015  3.0  0.0       NaN    normal  notpresent  notpresent   
18   60.0  100.0  1.025  0.0  3.0       NaN    normal  notpresent  notpresent   
19   62.0   60.0  1.015  1.0  0.0       NaN  abnormal     present  notpresent   
20   61.0   80.0  1.015  2.0  0.0  abnormal  abnormal  notpresent  notpresent   
22   48.0   80.0  1.025  4.0  0.0    normal  abnormal  notpresent  notpresent   
24   42.0  100.0  1.015  4.0  0.0    normal  abnormal  notpresent     present   
25   61.0   60.0  1.025  0.0  0.0       NaN    normal  notpresent  notpresent   
26   75.0   80.0  1.015  0.0  0.0       NaN    normal  notpresent  notpresent   
27   69.0   70.0  1.010  3.0  4.0    normal  abnormal  notpresent  notpresent   
31   73.0   90.0  1.015  3.0  0.0       NaN  abnormal     present  notpresent   
32   61.0   90.0  1.010  1.0  1.0       NaN    normal  notpresent  notpresent   
35   65.0   90.0  1.020  2.0  1.0  abnormal    normal  notpresent  notpresent   
39   82.0   80.0  1.010  2.0  2.0    normal       NaN  notpresent  notpresent   
40   46.0   90.0  1.010  2.0  0.0    normal  abnormal  notpresent  notpresent   
42   47.0  100.0  1.010  0.0  0.0       NaN    normal  notpresent  notpresent   
43   35.0   80.0  1.010  1.0  0.0  abnormal       NaN  notpresent  notpresent   
46   48.0   70.0  1.015  0.0  0.0       NaN    normal  notpresent  notpresent   
48   73.0   70.0  1.005  0.0  0.0    normal    normal  notpresent  notpresent   
49   60.0   70.0  1.010  2.0  0.0    normal  abnormal     present  notpresent   
52   53.0   90.0  1.015  0.0  0.0       NaN    normal  notpresent  notpresent   
53   62.0   80.0  1.015  0.0  5.0       NaN       NaN  notpresent  notpresent   
54   63.0   80.0  1.010  2.0  2.0    normal       NaN  notpresent  notpresent   
56   76.0   70.0  1.015  3.0  4.0    normal  abnormal     present  notpresent   
58   73.0   80.0  1.020  2.0  0.0  abnormal  abnormal  notpresent  notpresent   
62   15.0   60.0  1.020  3.0  0.0       NaN    normal  notpresent  notpresent   
69   26.0   70.0  1.015  0.0  4.0       NaN    normal  notpresent  notpresent   
70   61.0   80.0  1.015  0.0  4.0       NaN    normal  notpresent  notpresent   
71   46.0   60.0  1.010  1.0  0.0    normal    normal  notpresent  notpresent   
74   56.0   90.0  1.015  2.0  0.0  abnormal  abnormal  notpresent  notpresent   
76   48.0   80.0  1.005  4.0  0.0  abnormal  abnormal  notpresent     present   
77   67.0   70.0  1.010  1.0  0.0       NaN    normal  notpresent  notpresent   
79   56.0   80.0  1.010  1.0  0.0       NaN    normal  notpresent  notpresent   
80   74.0   80.0  1.010  0.0  0.0       NaN    normal  notpresent  notpresent   
84   59.0   70.0  1.010  3.0  0.0    normal  abnormal  notpresent  notpresent   
87   70.0  100.0  1.005  1.0  0.0    normal  abnormal     present  notpresent   
90   63.0  100.0  1.010  2.0  2.0    normal    normal  notpresent     present   
91   56.0   70.0  1.015  4.0  1.0  abnormal    normal  notpresent  notpresent   
92   71.0   70.0  1.010  3.0  0.0    normal  abnormal     present     present   
93   73.0  100.0  1.010  3.0  2.0  ab

# Train model using main clinical features

In [243]:
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier 
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
import pickle

In [244]:
X=df.loc[:,["sg","al","sc", "hemo", "pcv", "rbcc"]]
Y=df.loc[:,["class"]]

In [245]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

In [246]:
model = LogisticRegression()
model.fit(X_train, np.ravel(Y_train))


LogisticRegression()

In [247]:
model = LogisticRegression()
model.fit(X_train, np.ravel(Y_train))

LogisticRegression()

In [248]:
probability = model.predict_proba(pd.DataFrame({"sg":[1], "al":[0],  "sc":[0], "hemo":[0], "pcv":[0],  "rbcc":[0],}))


In [249]:
probability

array([[1.00000000e+00, 3.81162851e-10]])

In [250]:
predict = model.predict(pd.DataFrame({ "sg":[1], "al":[1], "sc":[1], "hemo":[1], "pcv":[1], "rbcc":[1],}))

In [251]:
predict

array([1])

In [252]:
predictions = model.predict(X_test)
predictions

array([2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1])

### Model evaluation metrics

#### Acuracy of used model

In [253]:


from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, predictions)

In [254]:
print(f'Accuracy: {accuracy}')

Accuracy: 0.9344262295081968


#### Precision of used model

In [255]:
from sklearn.metrics import precision_score
precision = precision_score(Y_test, predictions)

In [256]:
print(f'Precision: {precision}')

Precision: 1.0


#### Recall of used model

In [257]:
from sklearn.metrics import recall_score
recall = recall_score(Y_test, predictions)

In [258]:
print(f'Recall: {recall}')

Recall: 0.8181818181818182


#### F1 score of used model

In [260]:
from sklearn.metrics import f1_score
f1 = f1_score(Y_test, predictions)

In [261]:
print(f'F1 Score: {f1}')

F1 Score: 0.9


#### Confusion matrix of used model

In [262]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(Y_test, predictions)

In [263]:
print(f'Confusion Matrix:\n{conf_matrix}')

Confusion Matrix:
[[18  4]
 [ 0 39]]


#### Correlation Coefficient of Used Model

In [264]:
from sklearn.metrics import matthews_corrcoef
mcc = matthews_corrcoef(Y_test, predictions)

In [265]:
print(f'Matthews Correlation Coefficient: {mcc}')

Matthews Correlation Coefficient: 0.8614359416734163


In [212]:
print(f'Size of y_test: {len(Y_test)}')

Size of y_test: 61
